[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile --force && pnpm run build"

[deploy]
startCommand = "node dist/migrate.js && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
